import {topic} from '../src/topics/mammals.js';
import {GameEngine} from '../src/core/game-engine.js';
import {applyTheme} from '../src/core/theme.js';
const report=document.getElementById('report'),results=[];
const assert=(ok,message)=>{if(!ok)throw Error(message)};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const until=async fn=>{let end=performance.now()+7000;while(!fn()){if(performance.now()>end)throw Error('Timed out');await wait(20)}};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const click=s=>{let el=q(s);assert(el&&!el.disabled,'Missing/enabled '+s);el.click()};
async function test(name,fn){try{await fn();results.push('PASS '+name)}catch(e){results.push('FAIL '+name+': '+e.message)}report.textContent=results.join('\n')}
applyTheme(topic);const game=new GameEngine(topic);game.init();game.audio.muted=true;
const begin=(mode,category='all',all=false)=>{game.start(mode);game.chooseCategory(category);if(['sort','identify','knowledge','spelling'].includes(mode))click(all?'[data-action="all-words"]':'[data-action="short"]')};
await test('Launch / twelve cards / coming-soon activities locked / Home',()=>{assert(!q('.mode-card'),'menu visible on launch');click('[data-action="launch"]');assert(qa('.mode-card').length===12,'cards');for(const id of ['story','video','phonics'])assert(q('[data-mode="'+id+'"]').disabled,id);assert(!q('[data-mode="detective"]').disabled,'Detective enabled');click('#home');assert(q('.welcome'),'Home')});
await test('Homeward assets preload before letter input; nine real chance tokens',async()=>{begin('spelling');assert(game.state.animating&&!q('.letter-key:not(:disabled)'),'input enabled while loading');await until(()=>q('.homeward-canvas')&&!game.state.animating);assert(qa('.chance-token').length===9,'nine tokens');assert(q('.guess-count').textContent==='9 chances left','counter');assert(game.homewardScene.images&&Object.keys(game.homewardScene.images).length===13,'all frames decoded');game.menu();});
await test('Detective silhouette: loading, wrong guess, reveal and one star',async()=>{game.start('detective');click('[data-reveal="silhouette"]');await until(()=>!q('[data-action="detective-guess"]').disabled);assert(q('canvas').getAttribute('aria-label')==='Mystery mammal picture','answer leak');click('[data-action="detective-guess"]');click('[data-detective-answer="Rhinoceros"]');assert(q('[data-detective-answer="Rhinoceros"]').disabled,'wrong guess not disabled');assert(game.state.score===0,'wrong guess awarded point');click('[data-detective-answer="Elephant"]');assert(game.state.score===1,'correct score');q('[data-detective-answer="Elephant"]').click();assert(game.state.score===1,'duplicate score');assert(!q('[data-action="detective-next"]').disabled,'next');click('[data-action="detective-next"]');assert(qa('[data-reveal]').length===3,'next choices');game.menu()});
await test('Detective mosaic: 120 tiles, pause, resume and exit cleanup',async()=>{game.start('detective');click('[data-reveal="mosaic"]');await until(()=>!q('[data-action="detective-pause"]').disabled);const d=game.detective;assert(d.order.length===120 && new Set(d.order).size===120,'120 distinct tiles');assert(d.clock.blocks===0,'start covered');click('[data-action="detective-pause"]');await until(()=>d.clock.blocks===1);click('[data-action="detective-pause"]');const frozen=d.clock.seconds;await wait(1150);assert(d.clock.seconds===frozen,'pause ran');click('[data-action="detective-pause"]');await until(()=>d.clock.blocks===2);click('[data-action="detective-guess"]');assert(d.clock.started===null,'guess must pause');click('[data-action="detective-reveal"]');assert(d.revealed && game.state.score===0,'manual reveal score');assert(q('#detective-progress').value===45,'full reveal progress');game.menu();assert(!d.active && d.timer===null,'exit cleanup')});
await test('Detective pixel: start, pause and back before image loads',async()=>{game.start('detective');click('[data-reveal="pixel"]');await until(()=>!q('[data-action="detective-pause"]').disabled);assert(qa('[data-duration]').length===3,'duration options');assert(game.detective.clock.duration===45,'default duration');click('[data-duration="60"]');assert(game.detective.clock.duration===60 && q('#detective-progress').max===60,'60s selection');click('[data-duration="30"]');assert(game.detective.clock.duration===30,'30s selection');click('[data-duration="45"]');click('[data-action="detective-pause"]');await until(()=>game.detective.clock.seconds>0.3);click('[data-action="detective-pause"]');assert(game.detective.clock.started===null,'pause');assert(q('.detective-durations').hidden,'duration changes during round');click('[data-action="detective-setup"]');click('[data-reveal="silhouette"]');game.menu();await wait(200);assert(q('.mode-grid'),'stale load overwrote menu')});
await test('Every category and all 123 teaching routes; results and replay',()=>{const seen=[];for(const c of topic.categories){begin('learn',c.id);while(game.state.screen!=='results'){seen.push(game.state.items[game.state.index].id);click('[data-action="next"]')}assert(document.activeElement.tagName==='H1','results focus')}assert(new Set(seen).size===123,'reachability');begin('learn');assert(game.state.items.length===123,'All Words');game.menu();});
await test('All 15 reading cards, supplied phrases and completion',()=>{game.start('create');for(let i=0;i<topic.curriculum.readingPractice.length;i++){assert(q('.sentence-reading'),'reading');click('[data-action="read-next"]')}assert(game.state.score===topic.curriculum.readingPractice.length&&game.state.screen==='results','reading results');click('[data-action="again"]');assert(q('.sentence-reading'),'reading replay');click('[data-action="back"]');assert(game.state.screen==='menu','reading back');game.start('learn');assert(!q('[data-action="reading"]'),'reading still in Meet the Words')});
await test('Every category/All path in all six vocabulary modes and Knowledge',()=>{for(const mode of ['learn','sort','identify','spelling','flip','wheel','knowledge'])for(const cat of [...topic.categories.map(x=>x.id),'all']){game.start(mode);assert(qa('[data-category]').length===topic.categories.length,'categories');game.chooseCategory(cat);if(['sort','identify','spelling','knowledge'].includes(mode))click('[data-action="all-words"]');if(mode==='flip')click('[data-action="flip-count"]');assert(game.state.items.length>0,'empty '+mode+cat);game.back();assert(qa('[data-category]').length===topic.categories.length,'back groups')}});
await test('Supplied pictures load across teaching, reading, choices, spelling, pairs and wheel',async()=>{
 game.start('learn');await until(()=>qa('.category-art').length===topic.categories.length && qa('.category-art').every(img=>img.complete&&img.naturalWidth===1024));
 for(const mode of ['learn','sort','identify','spelling','flip','wheel']) {
  begin(mode,'mammals');if(mode==='flip')click('[data-action="flip-count"]');
  await until(()=>qa('#content img:not(.chance-token)').length>0 && qa('#content img:not(.chance-token)').every(img=>img.complete&&img.naturalWidth===1024));
  assert(!q('#content .missing-art'),'missing art '+mode);
 }
 game.start('create');await until(()=>q('.reading-art')?.complete&&q('.reading-art').naturalWidth===1024);
 begin('knowledge');game.state.items=[topic.knowledgeQuestions.find(question=>question.choices.every(choice=>choice.image))];game.state.index=0;game.round();await until(()=>qa('.answer-art').length===3 && qa('.answer-art').every(img=>img.complete&&img.naturalWidth===1024));
 game.menu();
});
await test('Short exit before/after answer; All Words does not reset queue',()=>{game.queues={};begin('sort');const first=game.state.items[0],second=game.state.items[1];game.menu();assert(game.queues['sort:all'][0].id===first.id,'unanswered missing');begin('sort');click('[data-answer="'+first.categoryId+'"]');game.menu();assert(game.queues['sort:all'][0].id===second.id,'answered returned');const saved=game.queues['sort:all'].map(x=>x.id).join();begin('sort','all',true);game.menu();assert(game.queues['sort:all'].map(x=>x.id).join()===saved,'all reset')});
await test('Identification: three unique choices and independent toggles',()=>{begin('identify');assert(qa('[data-answer]').length===3,'choice count');assert(new Set(qa('[data-answer]').map(x=>x.dataset.answer)).size===3,'duplicate');click('[data-action="target-toggle"]');assert(q('.identify-target').classList.contains('concealed'),'target');assert(!q('.answers').classList.contains('conceal-answers'),'independence');click('[data-action="answers-toggle"]');assert(getComputedStyle(q('.answer-art')).display==='none','answer picture space');assert(q('.answer').getBoundingClientRect().height>=44,'hit area');});
await test('Wrong retry, first-try scoring, answer once; Knowledge explanation',()=>{begin('knowledge','all',true);const item=game.state.items[0];click('[data-answer]:not([data-answer="'+item.correctChoiceId+'"])');click('[data-answer="'+item.correctChoiceId+'"]');assert(game.state.score===0,'retry scored');assert(q('#feedback').textContent.includes(item.explanation),'explanation');click('[data-action="continue"]');const next=game.state.items[1];click('[data-answer="'+next.correctChoiceId+'"]');assert(game.state.score===1,'score');assert(qa('[data-answer]').every(x=>x.disabled),'repeat allowed');});
await test('Homeward normal hops, repeated letters, input locks, final entry and win exactly once',async()=>{begin('spelling','all',true);game.state.items=[topic.items.find(x=>x.id==='hippopotamus')];game.state.index=0;game.state.score=0;game.round();game.guess('p');assert(qa('.letter-slot').filter(x=>x.textContent==='P').length===3,'all repeats');game.guess('o');assert(!game.state.guessed.includes('o'),'hop did not lock');await until(()=>!game.state.animating);const position=game.homewardScene.pose.x;game.guess('p');assert(game.homewardScene.pose.x===position&&!game.state.animating&&game.state.misses===0,'repeat moved or consumed chance');game.guess('z');game.guess('x');assert(game.state.misses===1,'wrong input lock');await until(()=>!game.state.animating);assert(game.homewardScene.pose.x>position&&game.homewardScene.pose.x<=800,'wrong hop or midpoint cap');for(const letter of new Set('hippopotamus')){game.guess(letter);await until(()=>!game.state.animating)}assert(game.state.spellingStatus==='won','win');assert(game.state.score===1&&game.homewardScene.pose.hidden,'entry/score');game.guess('h');assert(game.state.score===1&&q('.homeward-trail.won'),'once/outcome');});
await test('Homeward exactly nine mistakes lose; reduced motion; exit mid-hop restores',async()=>{game.reduced=()=>true;begin('spelling','all',true);game.state.items=[topic.items.find(x=>x.id==='cat')];game.state.index=0;game.round();for(const l of 'bdefghij'){game.guess(l);await until(()=>!game.state.animating)}assert(!game.state.spellingStatus&&game.state.misses===8,'early loss');game.guess('k');assert(game.state.spellingStatus==='lost'&&game.state.score===0&&game.state.misses===9,'ninth loss');assert(q('.homeward-trail.lost')&&q('[data-action="continue"]'),'loss Next');assert(game.homewardScene.pose.hidden&&game.homewardScene.pose.foxX===1455,'loss pose');game.reduced=()=>false;game.queues={};begin('spelling');const id=game.state.items[0].id;game.guess(game.state.items[0].name.match(/[a-z]/)[0]);const oldScene=game.homewardScene;game.menu();await wait(450);assert(game.state.screen==='menu'&&game.timers.size===0&&!oldScene.active&&oldScene.frame===null&&!game.homewardScene,'stale callback');assert(game.queues['spelling:all'][0].id===id,'lost unanswered word');});
await test('Flip 10/20/30 pair counts; teacher-paced mismatches; unmatched exit restore',async()=>{for(const n of [10,20,30]){game.queues={};begin('flip');game.startFlip(n);assert(qa('.tile').length===n*2,'board '+n);const a=game.state.tiles[0],b=game.state.tiles.find(x=>x.item.id!==a.item.id);game.flip(a.id);game.flip(b.id);await wait(400);assert(a.open&&b.open,'auto hidden');game.flip(a.id);assert(a.open&&b.open,'open tile closed mismatch');const c=game.state.tiles.find(x=>x.id!==a.id&&x.id!==b.id);game.flip(c.id);assert(!a.open&&!b.open&&c.open,'next closes');game.menu();assert(game.queues['flip:all'].length===123,'restoration');}});
await test('Flip complete board scores each pair once',async()=>{game.queues={};begin('flip','young');game.startFlip(8);game.reduced=()=>true;for(const item of [...game.state.items]){const pair=game.state.tiles.filter(x=>x.item.id===item.id);game.flip(pair[0].id);game.flip(pair[1].id);await until(()=>!game.state.locked)}assert(game.state.score===8,'score');click('[data-action="continue"]');assert(game.state.screen==='results','results');game.reduced=()=>false;});
await test('Wheel real normal spin, hold and text-only silent reveal',async()=>{begin('wheel','young');let calls=0;const speak=game.audio.speak;game.audio.speak=()=>calls++;click('[data-action="spin"]');assert(q('[data-action="spin"]').disabled,'spin lock');await until(()=>!!game.state.selected);assert(q('.reading-word')&&!q('#content img')&&!q('#content .missing-art'),'not text only');assert(calls===0,'spoken');click('[data-action="wheel-next"]');assert(game.state.remaining.length===7,'not removed');game.audio.speak=speak;});
await test('Wheel all 123 items, explicit batches and final removal (fixture-selected items)',()=>{begin('wheel');const seen=[];while(game.state.screen!=='results'){const item=game.state.wheelPool[0];seen.push(item.id);game.state.selected=item;game.wheel();game.nextWheel()}assert(new Set(seen).size===123&&seen.length===123,'exhaustion');assert(game.state.score===123,'score');});
await test('Keyboard M/F during spelling, Escape, mute, repeated Home cleanup',async()=>{begin('spelling');document.dispatchEvent(new KeyboardEvent('keydown',{key:'m',bubbles:true}));assert(game.state.guessed.includes('m'),'M not a letter');await until(()=>!game.state.animating);document.dispatchEvent(new KeyboardEvent('keydown',{key:'f',bubbles:true}));assert(game.state.guessed.includes('f'),'F not a letter');game.menu();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(game.state.screen==='launch','Escape');for(let i=0;i<12;i++){game.menu();begin('wheel');game.spin();game.launch();assert(game.timers.size===0,'timers');assert(qa('.welcome').length===1,'duplicate')}const before=game.audio.muted;click('#mute');assert(game.audio.muted!==before,'mute');});
await test('Full completion and results for all sort/identify words and all knowledge questions',()=>{for(const mode of ['sort','identify','knowledge']){begin(mode,'all',true);const total=game.state.items.length;while(game.state.screen!=='results'){const item=game.state.items[game.state.index];const id=mode==='sort'?item.categoryId:mode==='knowledge'?item.correctChoiceId:item.id;click('[data-answer="'+id+'"]');click('[data-action="continue"]')}assert(game.state.score===total,'completion '+mode);click('[data-action="menu"]');assert(game.state.screen==='menu','menu return')}});
await test('Different synthetic pack, changed categories/words/assets, no scenery, same supported skin with four tries',()=>{const changed=structuredClone(topic);changed.title='Synthetic test';changed.categories=changed.categories.slice(0,2);changed.items=[...topic.items.slice(0,3),...topic.items.filter(x=>x.categoryId==='bodies').slice(0,3)].map(x=>({...x,image:'assets/test/'+x.id+'.png'}));changed.modeSkins.spelling.attempts=4;const prior=game.topic;game.topic=changed;game.launch();assert(q('h1').textContent==='Synthetic test','title');game.start('spelling');assert(qa('[data-category]').length===2,'categories');game.chooseCategory('all');click('[data-action="short"]');assert(q('.guess-count').textContent.includes('4'),'skin config');game.menu();game.topic=prior;game.launch();});
game.clean();report.textContent=results.join('\n')+'\nDONE '+results.filter(x=>x.startsWith('PASS')).length+'/'+results.length;report.dataset.done='true';
