// Generated by scripts/import-landing-animations.py.
export const landingAssets = {
  "squirrel-idle": {
    "file": "assets/topics/mammals/landing-animations/squirrel-idle.webp",
    "cell": 160,
    "columns": 4,
    "durations": [
      120,
      120,
      120,
      120,
      120,
      120,
      120,
      120,
      120,
      120,
      120,
      120
    ]
  },
  "squirrel-acorn-run": {
    "file": "assets/topics/mammals/landing-animations/squirrel-acorn-run.webp",
    "cell": 160,
    "columns": 4,
    "durations": [
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65
    ]
  },
  "mouse-run": {
    "file": "assets/topics/mammals/landing-animations/mouse-run.png",
    "cell": 313.5,
    "columns": 4,
    "durations": Array(16).fill(70)
  },
  "bat-flight": {
    "file": "assets/topics/mammals/landing-animations/bat-flight.webp",
    "cell": 160,
    "columns": 4,
    "durations": [
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65
    ]
  }
};
