"""Verify supplied originals and create separately named lossless WebP delivery files."""
from pathlib import Path
from PIL import Image
import hashlib, json

source = Path('docs/homeward-trail-originals/Homeward_Trail_Assets')
output = Path('assets/topics/mammals/homeward-trail')
output.mkdir(parents=True, exist_ok=True)
manifest = json.loads((source / 'manifest.json').read_text())
# Torso spans and body-centred ground anchors, measured on the supplied alpha crops.
# These are per-pose registration values, not identical full-canvas image sizes.
registration = {
 'rabbit-sit-right': (690, .49, 1.0),
 'rabbit-hop-01-takeoff': (790, .53, 1.0),
 'rabbit-hop-02-airborne': (850, .50, 1.0),
 'rabbit-hop-03-landing': (800, .50, 1.0),
 'rabbit-entry-01-crouch': (850, .48, 1.0),
 'rabbit-entry-02-rear-quarter': (790, .52, 1.0),
 'rabbit-entry-03-tail': (830, .50, 1.0),
 'rabbit-escape-01-push-off': (880, .52, 1.0),
 'rabbit-escape-02-flight': (910, .51, 1.0),
 'rabbit-escape-03-landing': (850, .51, 1.0),
 'fox-appear-left': (940, .46, 1.0),
}
records = {}
for key, data in manifest.items():
 original = source / data['file']
 digest = hashlib.sha256(original.read_bytes()).hexdigest()
 if digest != data['sha256']: raise ValueError('Original checksum mismatch: ' + key)
 image = Image.open(original).convert('RGBA')
 if image.size != (data['width'], data['height']): raise ValueError('Dimension mismatch: ' + key)
 bounds = tuple(data['alphaBounds'])
 crop = image.crop(bounds)
 if key != 'woodland-background': crop.thumbnail((640, 640) if key != 'chance-token' else (96,96), Image.Resampling.LANCZOS)
 target = output / (key + '.webp')
 crop.save(target, format='WEBP', lossless=True, method=6)
 entry = {'file': str(target).replace('\\','/'), 'originalFile': str(original).replace('\\','/'),
          'originalSha256': digest, 'originalDimensions': list(image.size), 'alphaBounds': list(bounds),
          'width': crop.width, 'height': crop.height, 'bytes': target.stat().st_size,
          'sha256': hashlib.sha256(target.read_bytes()).hexdigest()}
 if key in registration:
  torso, ax, ay = registration[key]
  entry.update({'torsoSpan': torso * crop.width / (bounds[2]-bounds[0]), 'anchor': [ax*crop.width, ay*crop.height]})
 records[key] = entry
archive = Path('C:/Users/Administrator/Downloads/Homeward_Trail_Animation_Assets.zip')
audit = {'source': str(archive), 'sourceSha256': hashlib.sha256(archive.read_bytes()).hexdigest(),
         'provenance': 'Supplied artwork; original PNGs retained byte-for-byte. Separately named cropped/resized lossless WebP derivatives.',
         'assets': records}
Path('docs/homeward-trail-assets.json').write_text(json.dumps(audit,indent=2)+'\n')
Path('src/core/skins/homeward-assets.js').write_text('// Generated by scripts/import-homeward-trail.py; supplied artwork registration.\nexport const trailAssets = '+json.dumps(records,indent=2)+';\n')
print('Verified 13 originals; delivery bytes:',sum(x['bytes'] for x in records.values()))
