"""Keep supplied originals; create aligned lossless delivery atlases."""
from pathlib import Path
from PIL import Image
import hashlib, json

root = Path(__file__).resolve().parents[1]
source = root / 'docs/landing-animation-originals/Mammals_Club_Landing_Animations'
manifest = json.loads((source / 'manifest.json').read_text())
output = root / 'assets/topics/mammals/landing-animations'
output.mkdir(parents=True, exist_ok=True)
hash_file = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
audit = {'sourceZip': 'Mammals_Club_Landing_Animations_48_Frames.zip', 'originals': {}, 'sequences': {}}
for path in source.rglob('*'):
    if path.is_file(): audit['originals'][path.relative_to(root).as_posix()] = hash_file(path)
for name, sequence in manifest['sequences'].items():
    atlas = Image.new('RGBA', (640, 480))
    frames = []
    for i, frame in enumerate(sequence['frames']):
        path = source / frame['file']
        with Image.open(path) as image:
            assert image.size == (480, 480)
            bounds = image.convert('RGBA').getchannel('A').getbbox()
            atlas.paste(image.resize((160, 160), Image.Resampling.LANCZOS), ((i % 4)*160, (i // 4)*160))
        frames.append({'original': path.relative_to(root).as_posix(), 'sha256': hash_file(path), 'alphaBounds': bounds, 'durationMs': frame['durationMs']})
    target = output / (name + '.webp')
    atlas.save(target, 'WEBP', lossless=True, method=6)
    audit['sequences'][name] = {'file': target.relative_to(root).as_posix(), 'sha256': hash_file(target), 'cell': 160, 'columns': 4, 'frames': frames}
(root / 'docs/landing-animation-assets.json').write_text(json.dumps(audit, indent=2)+'\n')
runtime = {name: {'file': s['file'], 'cell': 160, 'columns': 4, 'durations': [f['durationMs'] for f in s['frames']]} for name, s in audit['sequences'].items()}
(root / 'src/core/landing-assets.js').write_text('// Generated by scripts/import-landing-animations.py.\nexport const landingAssets = '+json.dumps(runtime, indent=2)+';\n')
print('Imported 48 unchanged frames into four aligned lossless atlases:', sum(p.stat().st_size for p in output.glob('*.webp')), 'bytes')
